config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
  get 'sessions/new'

  resources :users
    root 'static_pages#home'
    get 'home', to: 'static_pages#home'
    get  'static_pages/help'
    get  'static_pages/about'
    get  'static_pages/contact'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
<<<<<<< HEAD
=======
=======
  resources :microposts
  resources :users
<<<<<<< HEAD
  get "/pages/:page" => "pages#show"
=======
>>>>>>> d9c4b2d1f7e70545700ffaee6ed09d3a59544a60
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0

end

app/models/user.rb
class User < ActiveRecord::Base
<<<<<<< HEAD
    attr_accessor :remember_token
=======
<<<<<<< HEAD
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
    has_secure_password
<<<<<<< HEAD
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
=======
    validates :password, presence: true, length: { minimum: 6 }
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
<<<<<<< HEAD
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    class << self
    # Returns the hash digest of the given string.
    def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # Returns a random token.
    def new_token
        SecureRandom.urlsafe_base64
    end
    end
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
def forget
    update_attribute(:remember_digest, nil)
end
=======
=======
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
<<<<<<< HEAD
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  # GET /users
  # GET /users.json
  def index
      @users = User.paginate(page: params[:page])  end
=======
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0

  # GET /users/1
  # GET /users/1.json
  def show
<<<<<<< HEAD
      @user = User.find(params[:id])
=======
<<<<<<< HEAD
      @user = User.find(params[:id])
=======
<<<<<<< HEAD
=======
    @microposts = Micropost.all
>>>>>>> d9c4b2d1f7e70545700ffaee6ed09d3a59544a60
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
    if @user.save
        log_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
    # Handle a successful save.
    else
    render 'new'
<<<<<<< HEAD
=======
=======
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
<<<<<<< HEAD
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
          flash[:success] = "Profile updated"
          redirect_to @user
          else
          render 'edit'
      end
  end
  
  def edit
      @user = User.find(params[:id])
=======
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
<<<<<<< HEAD
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
  end
  
  def logged_in_user
      unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
      end
  end
  
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
=======
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
<<<<<<< HEAD
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
   
=======
<<<<<<< HEAD
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
=======
      params.require(:user).permit(:name, :email)
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
    end
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
end

app/helpers/users_helper.rb
module UsersHelper
<<<<<<< HEAD
    
    # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end
=======
<<<<<<< HEAD
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
=======
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
end
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<<<<<<< HEAD
<%= render 'shared/error_messages', object: @user %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit yield(:button_text), class: "btn btn-primary" %>
=======
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
<% end %>

app/views/users/_user.html.erb
<li>
<%= gravatar_for user, size: 50 %>
<%= link_to user.name, user %>
| <%= link_to "delete", user, method: :delete,
data: { confirm: "You sure?" } %>
</li>

app/views/users/edit.html.erb
<<<<<<< HEAD
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= render 'form' %>
<div class="gravatar_edit">
<%= gravatar_for @user %>
<a href="http://gravatar.com/emails" target="_blank">Change</a>
</div>
</div>
</div>
=======
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0

app/views/users/index.html.erb
<<<<<<< HEAD
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
<%= render @users %>
</ul>

<%= will_paginate %>
=======
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
<<<<<<< HEAD
        <td><%= link_to 'Show', user %></td>
=======
<<<<<<< HEAD
        <td><%= link_to 'Show', user %></td>
=======
        <td><%= link_to 'Show', user, {:action => 'show'} %></td>
>>>>>>> d9c4b2d1f7e70545700ffaee6ed09d3a59544a60
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0

app/views/users/new.html.erb
<<<<<<< HEAD
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= render 'form' %>
</div>
</div>
=======
<<<<<<< HEAD
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for(@user, url: signup_path) do |f| %>
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
</div>
</div>
=======
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0

app/views/users/show.html.erb
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
<<<<<<< HEAD
</div>
=======
</div>
=======
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<<<<<<< HEAD
=======
<p>
  <strong>Microposts:</strong>
	<ul>
		<% @microposts.each do |t| %>
			<% if t.user_id == @user.id %>
				<li><%= t.content %> </li>
			<%end%>
		<%end%>
	</ul>
</p>

>>>>>>> d9c4b2d1f7e70545700ffaee6ed09d3a59544a60
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0