config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
  get 'sessions/new'

  resources :users
    root 'static_pages#home'
    get 'home', to: 'static_pages#home'
    get  'static_pages/help'
    get  'static_pages/about'
    get  'static_pages/contact'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
<<<<<<< HEAD
=======
=======
  resources :microposts
  resources :users
<<<<<<< HEAD
  get "/pages/:page" => "pages#show"
=======
>>>>>>> d9c4b2d1f7e70545700ffaee6ed09d3a59544a60
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", '/home' %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
<<<<<<< HEAD
            <li><%= link_to "Users", users_path %></li>
=======
            <li><%= link_to "Users", '#' %></li>
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
<<<<<<< HEAD
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
=======
                    <li><%= link_to "Settings", '#' %></li>
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
                    <li class="divider"></li>
                    <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                    </li>
                </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", '/login' %></li>
        <% end %>
        </ul>
    </nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                            'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "sample app", '/home', id: "logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '/home' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if logged_in? %>
<<<<<<< HEAD
            <li><%= link_to "Users", users_path %></li>
=======
            <li><%= link_to "Users", '#' %></li>
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
<<<<<<< HEAD
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
=======
                        <li><%= link_to "Settings", '#' %></li>
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0
                        <li class="divider"></li>
                        <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                        </li>
                    </ul>
                </li>
        <% else %>
            <li><%= link_to "Log in", '/login' %></li>
        <% end %>
        </ul>
    </nav>
    </div>
    </header>
    <div class="container">
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
</div>
</body>
<<<<<<< HEAD
</html>
=======
</html>
=======
<<<<<<< HEAD
  <title>SampleApp</title>
=======
  <title>DemoApp</title>
>>>>>>> d9c4b2d1f7e70545700ffaee6ed09d3a59544a60
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<<<<<<< HEAD
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
				<li><%= link_to "Home", '#' %></li>
				<li><%= link_to "Help", '#' %></li>
				<li><%= link_to "Sign in", '#' %></li>
				</ul>
			</nav>
		</div>
	
	</div>
	
</header>

<div class="center hero-unit">
	<h1>Welcome to the Sample App</h1>

	<h2>
		This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
	</h2>

	<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
	
</div>


<div class="container">
	<%= yield %>
</div>
=======
<%= yield %>
>>>>>>> d9c4b2d1f7e70545700ffaee6ed09d3a59544a60

</body>
</html>
>>>>>>> 4cc34a407957ef17da36e70102c9e7246b69aedd
>>>>>>> 8427a5e67ccc87e588511bf7900c6abab4fe4bc0